//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtivSem03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBProdutos
    {
        public int Id { get; set; }
        public string NomeProduto { get; set; }
        public int quantidade { get; set; }
        public double Valor { get; set; }
    }
}
